-- Supabase Table Setup for Timeline Items

CREATE TABLE IF NOT EXISTS timeline_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TIMESTAMPTZ NOT NULL,
  category TEXT DEFAULT 'General',
  description TEXT DEFAULT '',
  tags TEXT[] DEFAULT '{}',
  visibility TEXT NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'private')),
  username TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Drop old 'icon' column if present from previous table version
ALTER TABLE timeline_items DROP COLUMN IF EXISTS icon;

-- Add new columns if missing
ALTER TABLE timeline_items ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE timeline_items ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'public';
ALTER TABLE timeline_items ADD COLUMN IF NOT EXISTS username TEXT DEFAULT NULL;

-- Enable full access by disabling RLS or adding explicit policies
ALTER TABLE timeline_items DISABLE ROW LEVEL SECURITY;


-- Supabase Table Setup for User Profiles

CREATE TABLE IF NOT EXISTS user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT UNIQUE,
  full_name TEXT DEFAULT '',
  bio TEXT DEFAULT '',
  avatar_url TEXT DEFAULT NULL,
  role TEXT DEFAULT 'user',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable RLS for user_profiles for full backend/public access
ALTER TABLE user_profiles DISABLE ROW LEVEL SECURITY;

-- Force Supabase PostgREST to immediately refresh its schema cache
NOTIFY pgrst, 'reload schema';
