-- Supabase Table Setup for Timeline Items

CREATE TABLE IF NOT EXISTS timeline_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TIMESTAMPTZ NOT NULL,
  category TEXT DEFAULT 'General',
  description TEXT DEFAULT '',
  visibility TEXT NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'private')),
  username TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable full access by disabling RLS or adding explicit policies for anon/authenticated roles
ALTER TABLE timeline_items DISABLE ROW LEVEL SECURITY;

-- Alternatively, if you want Row Level Security (RLS) enabled, run the policies below:
/*
ALTER TABLE timeline_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select" ON timeline_items;
CREATE POLICY "Allow public select" ON timeline_items FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow public insert" ON timeline_items;
CREATE POLICY "Allow public insert" ON timeline_items FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update" ON timeline_items;
CREATE POLICY "Allow public update" ON timeline_items FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
*/
